export enum UserActionPermissions {
    CREATE_BOOK = 'CREATE_BOOK',
    UPDATE_BOOK = 'UPDATE_BOOK',
    DELETE_BOOK = 'DELETE_BOOK',
    CREATE_BOOK_REVIEW = 'CREATE_BOOK_REVIEW',
    UPDATE_BOOK_REVIEW = 'UPDATE_BOOK_REVIEW',
    DELETE_BOOK_REVIEW = 'DELETE_BOOK_REVIEW',
}
